### ISSUE TITLE
how do i login?

### ISSUE THREAD

**Issue by ralyodio** [lumehq/lume#185]
I'm using the .deb version 3.0.0 on arch.

It asks me for a nostr address `satoshi@nostr.me` i tried `profullstack@stacker.news` as that's the only email looking thing I know of....how can I get one of these nostr email thingies?

I'm using getalby extension if that helps.

**Comment by reyamir** [comment]
Hi, sorry for some UI part make you confused. I'm still trying to improve it in the next update.

If you're new to Nostr, you can click "Join Nostr" button to create new account, and in Nostr, we not use Email/Password like other platform, instead of it, we use Public Key/Private Key. To login, you will need to provide your Private Key.

The nostr address like `satoshi@nostr.me` is a new way to login, which using email/password like the old way, but it still in early stage and not widely adopted across all nostr clients.

And the nsecbunker token is provide by service like https://nsecbunker.com/, it is kind of service provide platform for manage your account keys.

So, to begin with Nostr, firstly you need to create a account keys by clicking to "Join Nostr", then follow other steps
<img width="1192" alt="Screenshot 2024-05-09 at 07 18 52" src="https://github.com/lumehq/lume/assets/123083837/713a9c97-8425-4c24-90b2-e0f0b026e418">

Then Lume will provide you a Private Key, you must keep this key in safeplace, you will need this key for login and use other nostr client.

You can explore all nostr apps here: https://www.nostrapps.com/ , which private key you can use all of its.

If you have more question, feel free to let me know. My english isn't good, but I will try to explain all about Nostr for you. 😊

**Comment by ralyodio** [comment]
i already have a nostr account through getalby.com -- how do I login with it?

**Comment by reyamir** [comment]
Ah, you can go to Key Management section then choose Nostr Settings: 
<img width="1031" alt="image" src="https://github.com/lumehq/lume/assets/123083837/c9b0167b-dca2-4fc1-9c94-2b7d4cfa988e">

Then, you can get Private Key and use it to login to Lume
<img width="1031" alt="image" src="https://github.com/lumehq/lume/assets/123083837/880d0e39-fd6b-4947-98b0-abacfc0b4d5c">

**Comment by ralyodio** [comment]
it doesn't work. i think i need both public and private key? what format do I use?

**Comment by reyamir** [comment]
Hi, You only need to paste the private key (as nsec1... format). If you get any error, can you help me screenshot it, maybe some bug prevent you login

**Comment by ralyodio** [comment]
i found my nsec1 key but it is only 63 bytes. I thought maybe I modified it accidentally so I created a new wallet and its key is only 63 bytes. the NDK package expects a 64 byte private key. Any idea how to fix?

**Comment by reyamir** [comment]
oh, seems strange
can you try other nostr client like https://nostter.app or https://snort.social? maybe lume have some bug with nsec parser not your key

**Comment by ralyodio** [comment]
Yeah I think its a bug with getalby.com -- I'm trying to create a login with NDK library and it throws an error.

**Comment by ralyodio** [comment]
so it looks like noStrudle key is 63 bytes too....I can login on lume with both alby and nostrudle keys, but when I try to post I get an error about no signer is defined.

**Comment by reyamir** [comment]
Hi, this is a bug in lume v3, I will push v4 today, happy have you try it out 😊
