### ISSUE TITLE
bug: theming in linux

### ISSUE THREAD

**Issue by gzuuus** [lumehq/lume#226]
Hi, I'm testing the new release (4.0.15) on Ubuntu (Tuxedo distro) with a system-wide dark theme. Unfortunately, Lume appears to be affected, making the UI difficult to use effectively.

![Screenshot_20240801_104711](https://github.com/user-attachments/assets/7e7a7100-2326-42c3-b93f-1bd5d6d36f01)
![Screenshot_20240801_104723](https://github.com/user-attachments/assets/c09e1641-864f-438d-8620-c15e0461ba46)
![Screenshot_20240801_105723](https://github.com/user-attachments/assets/5e0b1540-22fd-4ed7-8b1d-8de08b49fec3)

This last one is with a light system theme
![Screenshot_20240801_105148](https://github.com/user-attachments/assets/c227c690-1b5e-4772-a1df-fc28b9017d8e)

**Comment by reyamir** [comment]
Oh, it seems child webview isn't working fine on linux, I will look for solution

**Comment by reyamir** [comment]
Hi, I've decided drop linux support in latest version. Instead of that, I will build another native client for linux only. You can read full changelog for latest version here: https://njump.me/nevent1qvzqqqqqqypzqynpqwlamjxly44kuz4l6lehjlyqmnzw4z8hctu8m4qsggstf4jlqyghwumn8ghj7mn0wd68ytnhd9hx2tcpzemhxue69uhhyetvv9ujumn0wd68ytnwv46z7qpq2p0ry276lee4tds8n5zjrentq3sg8dkhm9e7ygrcq0y57859nujqs7r7gq
